# 定义编译器  
CC=gcc  
  
# 定义编译选项  
CFLAGS=-I.  
  
# 定义链接选项（这里留空）  
LDFLAGS=  
  
# 定义目标文件  
OBJECTS=eth_recv_send.o rs485_recv_send.o can_recv_send.o  
  
# 默认目标  
all: $(OBJECTS)  
  
# 编译C源文件生成目标文件  
%.o: %.c  
	$(CC) $(CFLAGS) -c -o $@ $<  
  
# 清理编译生成的文件  
clean:  
	rm -f $(OBJECTS)  
